server:
  port: 8899
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/personmanager
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver